//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string content { get; set; }
        public long customerId { get; set; }
        public int newId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string modifyBy { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual News News { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
