//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public long id { get; set; }
        public Nullable<int> providerId { get; set; }
        public int price { get; set; }
        public int amount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string modifyBy { get; set; }
        public Nullable<bool> available { get; set; }
        public string materialName { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
