//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Barcodes = new HashSet<Barcode>();
            this.DuePayments = new HashSet<DuePayment>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long id { get; set; }
        public Nullable<long> customerId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string address { get; set; }
        public Nullable<int> paymentMethodId { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<int> amount { get; set; }
        public string description { get; set; }
        public Nullable<int> statusId { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> shippingId { get; set; }
        public Nullable<long> employeeIdConfirm { get; set; }
        public Nullable<long> employeeIdShipping { get; set; }
        public Nullable<int> totalDebt { get; set; }
        public string type { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barcode> Barcodes { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuePayment> DuePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PayMentMethod PayMentMethod { get; set; }
        public virtual ShippingAdress ShippingAdress { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
