//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long id { get; set; }
        public long orderId { get; set; }
        public int productId { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> price { get; set; }
        public string type { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> totalPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
