//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRollsWorker
    {
        public int id { get; set; }
        public System.DateTime month { get; set; }
        public int workerId { get; set; }
        public string dayOff { get; set; }
        public string dayWork { get; set; }
        public Nullable<int> hourOfDay { get; set; }
        public Nullable<long> salaryToMonth { get; set; }
        public string unitSalary { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<int> standardWorkDay { get; set; }
        public Nullable<int> totalWorkDay { get; set; }
        public Nullable<long> baseSalary { get; set; }
        public Nullable<long> mainSalary { get; set; }
        public Nullable<long> subsidySalary { get; set; }
        public Nullable<int> totalOverTime { get; set; }
        public Nullable<long> overtimePay { get; set; }
        public Nullable<long> totalSalary { get; set; }
        public string description { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
