//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int id { get; set; }
        public int workerId { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string title { get; set; }
        public string status { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
