//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.PayRollsWorkers = new HashSet<PayRollsWorker>();
            this.Works = new HashSet<Work>();
        }
    
        public int id { get; set; }
        public string workerName { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dayOfBirth { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<long> contactSalary { get; set; }
        public string unitSalary { get; set; }
        public Nullable<int> workTime { get; set; }
        public string schedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRollsWorker> PayRollsWorkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Works { get; set; }
    }
}
